############################################################
#----------KillearPvP config enderpearl--------------------#
#-----------By: @Killearnith & @albert293------------------#
############################################################
#Cooldown de la enderpearl (en segundos)--------------------
#Enderpearls time cooldown.
duracion: 15
#Cooldown de la manzanda dorada encantada (en segundos)--------------------
#Enchanted Golden Apple time cooldown.
duraciongapple: 10
#Mensaje de texto del cooldown de la ender pearl y manzana encantada. (%tiempo% es el tiempo restante).
#Text when enderpearl/enchanted golden apple is on cooldown (%tiempo% is the time remaining).

mensaje: "§6[§5§lAlpina§f§lCraft§6] §dPuedes usar otra enderpearl en §e%tiempo%."
mensajegapple: "§6[§5§lAlpina§f§lCraft§6] §dPuedes usar otra gapple en §e%tiempo%."