name: KillearPvP
version: ${project.version}
main: killearzone.killearpvp.KillearPvP
api-version: 1.16
authors: [ Killearnith ]
description: This plugin makes the user choose the invulnerability frames of a mob/player.
